---
workstations:
  hosts:
    dell:
      ansible_host: 192.168.1.18
      ansible_connection: ssh
      ansible_user: $USER
    nitro:
      ansible_host: 192.168.1.8
      ansible_connection: ssh
      ansible_user: $USER