---
workstations:
  hosts:
    # dell:
    #   ansible_host: 192.168.1.18
    #   ansible_connection: ssh
    #   ansible_user: $USER
    nitro:
      ansible_host: 192.168.1.15
      ansible_connection: ssh
      pre_tasks:
      - name: Stop packagekit
        systemd:
          name: packagekit
          state: stopped
          enabled: no
        become: true
        ignore_errors: yes