---
- name: Configure Workstation
  hosts: workstations
  become: true
  become_method: sudo

  pre_tasks:
    - name: Debug OS info
      ansible.builtin.debug:
        msg: "OS Distribution: {{ ansible_distribution | lower }}"
    
    - name: Include distribution specific variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../group_vars/distros/{{ ansible_distribution | lower | replace(' ', '') }}.yml"
        
    - name: Detect OS distribution
      ansible.builtin.set_fact:
        os_distribution: "{{ ansible_distribution | lower }}"
        os_version: "{{ ansible_distribution_version }}"
      
    - name: Debug file path
      debug:
        msg: "{{ playbook_dir }}"

    - name: Include distribution specific variables
      ansible.builtin.include_vars:
        file: "../group_vars/distros/linuxmint.yml"

  roles:
    - common
    - system
    - vscode
    # - workstation
    - devops