---
- name: Handle missing GPG keys
  block:
    - name: Get missing GPG keys
      ansible.builtin.shell: |
        apt-get update 2>&1 | sed -En 's/.*NO_PUBKEY ([[:xdigit:]]+).*/\1/p' | sort -u
      register: missing_keys
      changed_when: false
      
    - name: Import GPG keys
      ansible.builtin.shell: |
        gpg --keyserver "hkps://keyserver.ubuntu.com:443" --recv-keys {{ item }}
        gpg --yes --output "/etc/apt/trusted.gpg.d/{{ item }}.gpg" --export {{ item }}
      loop: "{{ missing_keys.stdout_lines }}"
      when: missing_keys.stdout_lines | length > 0
  become: true
  tags: 
    - system
    - keys